AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
